{
    'name': 'Vighnahar Agro',
    'version': '1.2',
    'category': 'Inventory/Purchase',
    'summary': 'Vighnahar Agro',
    'depends': ['base', 'web', 'mail', 'website_google_map', 'base_geolocalize'],
    'data': [
        'views/menu_items.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/product_views.xml',
        'views/supplier_invoice_views.xml',
        'views/customer_invoice_views.xml',
        'views/uom_views.xml',
        'views/party_views.xml',
        'views/inventory_stock_location_views.xml',
        'views/bank_views.xml',
        'views/accounts_views.xml', 
        'report/customer_invoice_templates.xml',
        'report/report.xml',
        
        #'data/ir_cron.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vighnahar_agro/static/src/css/custom_styles.css',
            'vighnahar_agro/static/src/img/logo.png"',
            'vighnahar_agro/static/src/fonts/NotoSansDevanagari-Regular.ttf',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'sequence': 1,
}