from . import supplier
from . import customer
from . import custom_product
from . import custom_uom
from . import inventory_stock_location
from . import custom_p2p
from . import custom_s2p
from . import custom_resource
from . import custom_physical_inventory
from . import sub_inventory
from . import custom_inventory_transfer
from . import dehusking_mfg
from . import cutting_mfg
